# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'CWidgetxGlfeO.ui'
##
## Created by: Qt User Interface Compiler version 6.4.3
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QGridLayout, QHBoxLayout, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QSlider,
    QTabWidget, QWidget)

class Ui_settings(object):
    def setupUi(self, settings):
        if not settings.objectName():
            settings.setObjectName(u"settings_window")
        settings.resize(840, 580)
        self.config = QTabWidget(settings)
        self.config.setObjectName(u"config")
        self.config.setGeometry(QRect(0, 0, 840, 540))
        self.config.setMinimumSize(QSize(420, 540))
        self.config.setStyleSheet(u"")
        self.config.setTabPosition(QTabWidget.North)
        self.delays = QWidget()
        self.delays.setObjectName(u"delays")
        self.delays_installFacebook = QWidget(self.delays)
        self.delays_installFacebook.setObjectName(u"delays_installFacebook")
        self.delays_installFacebook.setGeometry(QRect(0, 55, 840, 42))
        self.delays_installFacebook_title = QLabel(self.delays_installFacebook)
        self.delays_installFacebook_title.setObjectName(u"delays_installFacebook_title")
        self.delays_installFacebook_title.setGeometry(QRect(0, 1, 200, 18))
        self.delays_installFacebook_title.setStyleSheet(u"")
        self.delays_installFacebook_horizontalSlider = QSlider(self.delays_installFacebook)
        self.delays_installFacebook_horizontalSlider.setObjectName(u"delays_installFacebook_horizontalSlider")
        self.delays_installFacebook_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_installFacebook_horizontalSlider.setStyleSheet(u"")
        self.delays_installFacebook_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_installFacebook_secs = QLabel(self.delays_installFacebook)
        self.delays_installFacebook_secs.setObjectName(u"delays_installFacebook_secs")
        self.delays_installFacebook_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_installFacebook_secs.setMinimumSize(QSize(0, 0))
        self.delays_installFacebook_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_installFacebook_devider = QLabel(self.delays_installFacebook)
        self.delays_installFacebook_devider.setObjectName(u"delays_installFacebook_devider")
        self.delays_installFacebook_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_installFacebook_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_refresh_config = QPushButton(self.delays)
        self.delays_refresh_config.setObjectName(u"delays_refresh_config")
        self.delays_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.delays_refresh_config.setStyleSheet(u"")
        self.delays_save_config = QPushButton(self.delays)
        self.delays_save_config.setObjectName(u"delays_save_config")
        self.delays_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.delays_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.delays_openFacebook = QWidget(self.delays)
        self.delays_openFacebook.setObjectName(u"delays_openFacebook")
        self.delays_openFacebook.setGeometry(QRect(0, 107, 840, 42))
        self.delays_openFacebook_title = QLabel(self.delays_openFacebook)
        self.delays_openFacebook_title.setObjectName(u"delays_openFacebook_title")
        self.delays_openFacebook_title.setGeometry(QRect(0, 1, 176, 18))
        self.delays_openFacebook_title.setStyleSheet(u"")
        self.delays_openFacebook_horizontalSlider = QSlider(self.delays_openFacebook)
        self.delays_openFacebook_horizontalSlider.setObjectName(u"delays_openFacebook_horizontalSlider")
        self.delays_openFacebook_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_openFacebook_horizontalSlider.setStyleSheet(u"")
        self.delays_openFacebook_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_openFacebook_devider = QLabel(self.delays_openFacebook)
        self.delays_openFacebook_devider.setObjectName(u"delays_openFacebook_devider")
        self.delays_openFacebook_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_openFacebook_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_openFacebook_secs = QLabel(self.delays_openFacebook)
        self.delays_openFacebook_secs.setObjectName(u"delays_openFacebook_secs")
        self.delays_openFacebook_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_openFacebook_secs.setMinimumSize(QSize(0, 0))
        self.delays_openFacebook_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_sendClick = QWidget(self.delays)
        self.delays_sendClick.setObjectName(u"delays_sendClick")
        self.delays_sendClick.setGeometry(QRect(0, 159, 840, 42))
        self.delays_sendClick_title = QLabel(self.delays_sendClick)
        self.delays_sendClick_title.setObjectName(u"delays_sendClick_title")
        self.delays_sendClick_title.setGeometry(QRect(0, 1, 112, 18))
        self.delays_sendClick_title.setStyleSheet(u"")
        self.delays_sendClick_horizontalSlider = QSlider(self.delays_sendClick)
        self.delays_sendClick_horizontalSlider.setObjectName(u"delays_sendClick_horizontalSlider")
        self.delays_sendClick_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_sendClick_horizontalSlider.setStyleSheet(u"")
        self.delays_sendClick_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_sendClick_devider = QLabel(self.delays_sendClick)
        self.delays_sendClick_devider.setObjectName(u"delays_sendClick_devider")
        self.delays_sendClick_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_sendClick_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_sendClick_secs = QLabel(self.delays_sendClick)
        self.delays_sendClick_secs.setObjectName(u"delays_sendClick_secs")
        self.delays_sendClick_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_sendClick_secs.setMinimumSize(QSize(0, 0))
        self.delays_sendClick_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_sendKeys = QWidget(self.delays)
        self.delays_sendKeys.setObjectName(u"delays_sendKeys")
        self.delays_sendKeys.setGeometry(QRect(0, 211, 840, 42))
        self.delays_sendKeys_title = QLabel(self.delays_sendKeys)
        self.delays_sendKeys_title.setObjectName(u"delays_sendKeys_title")
        self.delays_sendKeys_title.setGeometry(QRect(0, 1, 176, 18))
        self.delays_sendKeys_title.setStyleSheet(u"")
        self.delays_sendKeys_horizontalSlider = QSlider(self.delays_sendKeys)
        self.delays_sendKeys_horizontalSlider.setObjectName(u"delays_sendKeys_horizontalSlider")
        self.delays_sendKeys_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_sendKeys_horizontalSlider.setStyleSheet(u"")
        self.delays_sendKeys_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_sendKeys_devider = QLabel(self.delays_sendKeys)
        self.delays_sendKeys_devider.setObjectName(u"delays_sendKeys_devider")
        self.delays_sendKeys_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_sendKeys_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_sendKeys_secs = QLabel(self.delays_sendKeys)
        self.delays_sendKeys_secs.setObjectName(u"delays_sendKeys_secs")
        self.delays_sendKeys_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_sendKeys_secs.setMinimumSize(QSize(0, 0))
        self.delays_sendKeys_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_getWord = QWidget(self.delays)
        self.delays_getWord.setObjectName(u"delays_getWord")
        self.delays_getWord.setGeometry(QRect(0, 263, 840, 42))
        self.delays_getWord_title = QLabel(self.delays_getWord)
        self.delays_getWord_title.setObjectName(u"delays_getWord_title")
        self.delays_getWord_title.setGeometry(QRect(0, 1, 256, 18))
        self.delays_getWord_title.setStyleSheet(u"")
        self.delays_getWord_horizontalSlider = QSlider(self.delays_getWord)
        self.delays_getWord_horizontalSlider.setObjectName(u"delays_getWord_horizontalSlider")
        self.delays_getWord_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_getWord_horizontalSlider.setStyleSheet(u"")
        self.delays_getWord_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_getWord_devider = QLabel(self.delays_getWord)
        self.delays_getWord_devider.setObjectName(u"delays_getWord_devider")
        self.delays_getWord_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_getWord_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_getWord_secs = QLabel(self.delays_getWord)
        self.delays_getWord_secs.setObjectName(u"delays_getWord_secs")
        self.delays_getWord_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_getWord_secs.setMinimumSize(QSize(0, 0))
        self.delays_getWord_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_getConfirmUrl = QWidget(self.delays)
        self.delays_getConfirmUrl.setObjectName(u"delays_getConfirmUrl")
        self.delays_getConfirmUrl.setGeometry(QRect(0, 315, 840, 42))
        self.delays_getConfirmUrl_title = QLabel(self.delays_getConfirmUrl)
        self.delays_getConfirmUrl_title.setObjectName(u"delays_getConfirmUrl_title")
        self.delays_getConfirmUrl_title.setGeometry(QRect(0, 1, 336, 18))
        self.delays_getConfirmUrl_title.setStyleSheet(u"")
        self.delays_getConfirmUrl_horizontalSlider = QSlider(self.delays_getConfirmUrl)
        self.delays_getConfirmUrl_horizontalSlider.setObjectName(u"delays_getConfirmUrl_horizontalSlider")
        self.delays_getConfirmUrl_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.delays_getConfirmUrl_horizontalSlider.setStyleSheet(u"")
        self.delays_getConfirmUrl_horizontalSlider.setOrientation(Qt.Horizontal)
        self.delays_getConfirmUrl_devider = QLabel(self.delays_getConfirmUrl)
        self.delays_getConfirmUrl_devider.setObjectName(u"delays_getConfirmUrl_devider")
        self.delays_getConfirmUrl_devider.setGeometry(QRect(0, 20, 840, 2))
        self.delays_getConfirmUrl_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_getConfirmUrl_secs = QLabel(self.delays_getConfirmUrl)
        self.delays_getConfirmUrl_secs.setObjectName(u"delays_getConfirmUrl_secs")
        self.delays_getConfirmUrl_secs.setGeometry(QRect(766, 0, 74, 20))
        self.delays_getConfirmUrl_secs.setMinimumSize(QSize(0, 0))
        self.delays_getConfirmUrl_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.delays_totalTime = QWidget(self.delays)
        self.delays_totalTime.setObjectName(u"delays_totalTime")
        self.delays_totalTime.setGeometry(QRect(0, 484, 840, 30))
        self.delays_totalTime_title = QLabel(self.delays_totalTime)
        self.delays_totalTime_title.setObjectName(u"delays_totalTime_title")
        self.delays_totalTime_title.setGeometry(QRect(0, 8, 208, 18))
        self.delays_totalTime_title.setStyleSheet(u"")
        self.delays_totalTime_devider = QLabel(self.delays_totalTime)
        self.delays_totalTime_devider.setObjectName(u"delays_totalTime_devider")
        self.delays_totalTime_devider.setGeometry(QRect(0, 28, 840, 2))
        self.delays_totalTime_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.delays_totalTime_secs = QLabel(self.delays_totalTime)
        self.delays_totalTime_secs.setObjectName(u"delays_totalTime_secs")
        self.delays_totalTime_secs.setGeometry(QRect(694, 0, 146, 28))
        self.delays_totalTime_secs.setStyleSheet(u"font-size: 24px;\n"
"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 0 8px;")
        self.delays_totalTime_secs.setAlignment(Qt.AlignCenter)
        self.config.addTab(self.delays, "")
        self.paths = QWidget()
        self.paths.setObjectName(u"paths")
        self.paths_save_config = QPushButton(self.paths)
        self.paths_save_config.setObjectName(u"paths_save_config")
        self.paths_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.paths_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.paths_refresh_config = QPushButton(self.paths)
        self.paths_refresh_config.setObjectName(u"paths_refresh_config")
        self.paths_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.paths_refresh_config.setStyleSheet(u"")
        self.pagination = QTabWidget(self.paths)
        self.pagination.setObjectName(u"pagination")
        self.pagination.setGeometry(QRect(0, 55, 840, 460))
        self.pagination.setStyleSheet(u"QTabWidget::tab-bar {\n"
"    alignment: center;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"       border: none;\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 0;\n"
"}")
        self.pagination.setTabPosition(QTabWidget.South)
        self.pagination.setTabShape(QTabWidget.Rounded)
        self.pagination.setElideMode(Qt.ElideNone)
        self.n1 = QWidget()
        self.n1.setObjectName(u"n1")
        self.paths_adbFolder = QWidget(self.n1)
        self.paths_adbFolder.setObjectName(u"paths_adbFolder")
        self.paths_adbFolder.setGeometry(QRect(0, 0, 840, 42))
        self.paths_adbFolder_lineEdit = QLineEdit(self.paths_adbFolder)
        self.paths_adbFolder_lineEdit.setObjectName(u"paths_adbFolder_lineEdit")
        self.paths_adbFolder_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_adbFolder_title = QLabel(self.paths_adbFolder)
        self.paths_adbFolder_title.setObjectName(u"paths_adbFolder_title")
        self.paths_adbFolder_title.setGeometry(QRect(0, 1, 24, 18))
        self.paths_adbFolder_title.setStyleSheet(u"")
        self.paths_adbFolder_devider = QLabel(self.paths_adbFolder)
        self.paths_adbFolder_devider.setObjectName(u"paths_adbFolder_devider")
        self.paths_adbFolder_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_adbFolder_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_adbFolder_ext = QLabel(self.paths_adbFolder)
        self.paths_adbFolder_ext.setObjectName(u"paths_adbFolder_ext")
        self.paths_adbFolder_ext.setGeometry(QRect(782, 0, 58, 20))
        self.paths_adbFolder_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_facebookApk = QWidget(self.n1)
        self.paths_facebookApk.setObjectName(u"paths_facebookApk")
        self.paths_facebookApk.setGeometry(QRect(0, 52, 840, 42))
        self.paths_facebookApk_lineEdit = QLineEdit(self.paths_facebookApk)
        self.paths_facebookApk_lineEdit.setObjectName(u"paths_facebookApk_lineEdit")
        self.paths_facebookApk_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_facebookApk_title = QLabel(self.paths_facebookApk)
        self.paths_facebookApk_title.setObjectName(u"paths_facebookApk_title")
        self.paths_facebookApk_title.setGeometry(QRect(-1, 1, 64, 18))
        self.paths_facebookApk_title.setStyleSheet(u"")
        self.paths_facebookApk_devider = QLabel(self.paths_facebookApk)
        self.paths_facebookApk_devider.setObjectName(u"paths_facebookApk_devider")
        self.paths_facebookApk_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_facebookApk_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_facebookApk_ext = QLabel(self.paths_facebookApk)
        self.paths_facebookApk_ext.setObjectName(u"paths_facebookApk_ext")
        self.paths_facebookApk_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_facebookApk_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_proxifierApk = QWidget(self.n1)
        self.paths_proxifierApk.setObjectName(u"paths_proxifierApk")
        self.paths_proxifierApk.setGeometry(QRect(0, 104, 840, 42))
        self.paths_proxifierApk_lineEdit = QLineEdit(self.paths_proxifierApk)
        self.paths_proxifierApk_lineEdit.setObjectName(u"paths_proxifierApk_lineEdit")
        self.paths_proxifierApk_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_proxifierApk_title = QLabel(self.paths_proxifierApk)
        self.paths_proxifierApk_title.setObjectName(u"paths_proxifierApk_title")
        self.paths_proxifierApk_title.setGeometry(QRect(-1, 1, 72, 18))
        self.paths_proxifierApk_title.setStyleSheet(u"")
        self.paths_proxifierApk_devider = QLabel(self.paths_proxifierApk)
        self.paths_proxifierApk_devider.setObjectName(u"paths_proxifierApk_devider")
        self.paths_proxifierApk_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_proxifierApk_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_proxifierApk_ext = QLabel(self.paths_proxifierApk)
        self.paths_proxifierApk_ext.setObjectName(u"paths_proxifierApk_ext")
        self.paths_proxifierApk_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_proxifierApk_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_chromeDriverExe = QWidget(self.n1)
        self.paths_chromeDriverExe.setObjectName(u"paths_chromeDriverExe")
        self.paths_chromeDriverExe.setGeometry(QRect(0, 156, 840, 42))
        self.paths_chromeDriverExe_lineEdit = QLineEdit(self.paths_chromeDriverExe)
        self.paths_chromeDriverExe_lineEdit.setObjectName(u"paths_chromeDriverExe_lineEdit")
        self.paths_chromeDriverExe_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_chromeDriverExe_title = QLabel(self.paths_chromeDriverExe)
        self.paths_chromeDriverExe_title.setObjectName(u"paths_chromeDriverExe_title")
        self.paths_chromeDriverExe_title.setGeometry(QRect(0, 1, 104, 18))
        self.paths_chromeDriverExe_title.setStyleSheet(u"")
        self.paths_chromeDriverExe_devider = QLabel(self.paths_chromeDriverExe)
        self.paths_chromeDriverExe_devider.setObjectName(u"paths_chromeDriverExe_devider")
        self.paths_chromeDriverExe_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_chromeDriverExe_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_chromeDriverExe_ext = QLabel(self.paths_chromeDriverExe)
        self.paths_chromeDriverExe_ext.setObjectName(u"paths_chromeDriverExe_ext")
        self.paths_chromeDriverExe_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_chromeDriverExe_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_paddleOcrDetFolder = QWidget(self.n1)
        self.paths_paddleOcrDetFolder.setObjectName(u"paths_paddleOcrDetFolder")
        self.paths_paddleOcrDetFolder.setGeometry(QRect(0, 208, 840, 42))
        self.paths_paddleOcrDetFolder_lineEdit = QLineEdit(self.paths_paddleOcrDetFolder)
        self.paths_paddleOcrDetFolder_lineEdit.setObjectName(u"paths_paddleOcrDetFolder_lineEdit")
        self.paths_paddleOcrDetFolder_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_paddleOcrDetFolder_title = QLabel(self.paths_paddleOcrDetFolder)
        self.paths_paddleOcrDetFolder_title.setObjectName(u"paths_paddleOcrDetFolder_title")
        self.paths_paddleOcrDetFolder_title.setGeometry(QRect(0, 1, 112, 18))
        self.paths_paddleOcrDetFolder_title.setStyleSheet(u"")
        self.paths_paddleOcrDetFolder_devider = QLabel(self.paths_paddleOcrDetFolder)
        self.paths_paddleOcrDetFolder_devider.setObjectName(u"paths_paddleOcrDetFolder_devider")
        self.paths_paddleOcrDetFolder_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_paddleOcrDetFolder_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_paddleOcrDetFolder_ext = QLabel(self.paths_paddleOcrDetFolder)
        self.paths_paddleOcrDetFolder_ext.setObjectName(u"paths_paddleOcrDetFolder_ext")
        self.paths_paddleOcrDetFolder_ext.setGeometry(QRect(782, 0, 58, 20))
        self.paths_paddleOcrDetFolder_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_paddleOcrRecFolder = QWidget(self.n1)
        self.paths_paddleOcrRecFolder.setObjectName(u"paths_paddleOcrRecFolder")
        self.paths_paddleOcrRecFolder.setGeometry(QRect(0, 260, 840, 42))
        self.paths_paddleOcrRecFolder_lineEdit = QLineEdit(self.paths_paddleOcrRecFolder)
        self.paths_paddleOcrRecFolder_lineEdit.setObjectName(u"paths_paddleOcrRecFolder_lineEdit")
        self.paths_paddleOcrRecFolder_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_paddleOcrRecFolder_title = QLabel(self.paths_paddleOcrRecFolder)
        self.paths_paddleOcrRecFolder_title.setObjectName(u"paths_paddleOcrRecFolder_title")
        self.paths_paddleOcrRecFolder_title.setGeometry(QRect(-1, 1, 112, 18))
        self.paths_paddleOcrRecFolder_title.setStyleSheet(u"")
        self.paths_paddleOcrRecFolder_devider = QLabel(self.paths_paddleOcrRecFolder)
        self.paths_paddleOcrRecFolder_devider.setObjectName(u"paths_paddleOcrRecFolder_devider")
        self.paths_paddleOcrRecFolder_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_paddleOcrRecFolder_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_paddleOcrRecFolder_ext = QLabel(self.paths_paddleOcrRecFolder)
        self.paths_paddleOcrRecFolder_ext.setObjectName(u"paths_paddleOcrRecFolder_ext")
        self.paths_paddleOcrRecFolder_ext.setGeometry(QRect(782, 0, 58, 20))
        self.paths_paddleOcrRecFolder_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_PaddleOcrDigitalDictTxt = QWidget(self.n1)
        self.paths_PaddleOcrDigitalDictTxt.setObjectName(u"paths_PaddleOcrDigitalDictTxt")
        self.paths_PaddleOcrDigitalDictTxt.setGeometry(QRect(0, 312, 840, 42))
        self.paths_PaddleOcrDigitalDictTxt_lineEdit = QLineEdit(self.paths_PaddleOcrDigitalDictTxt)
        self.paths_PaddleOcrDigitalDictTxt_lineEdit.setObjectName(u"paths_PaddleOcrDigitalDictTxt_lineEdit")
        self.paths_PaddleOcrDigitalDictTxt_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_PaddleOcrDigitalDictTxt_title = QLabel(self.paths_PaddleOcrDigitalDictTxt)
        self.paths_PaddleOcrDigitalDictTxt_title.setObjectName(u"paths_PaddleOcrDigitalDictTxt_title")
        self.paths_PaddleOcrDigitalDictTxt_title.setGeometry(QRect(-1, 1, 184, 18))
        self.paths_PaddleOcrDigitalDictTxt_title.setStyleSheet(u"")
        self.paths_PaddleOcrDigitalDictTxt_devider = QLabel(self.paths_PaddleOcrDigitalDictTxt)
        self.paths_PaddleOcrDigitalDictTxt_devider.setObjectName(u"paths_PaddleOcrDigitalDictTxt_devider")
        self.paths_PaddleOcrDigitalDictTxt_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_PaddleOcrDigitalDictTxt_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_PaddleOcrDigitalDictTxt_ext = QLabel(self.paths_PaddleOcrDigitalDictTxt)
        self.paths_PaddleOcrDigitalDictTxt_ext.setObjectName(u"paths_PaddleOcrDigitalDictTxt_ext")
        self.paths_PaddleOcrDigitalDictTxt_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_PaddleOcrDigitalDictTxt_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_emailsTxt = QWidget(self.n1)
        self.paths_emailsTxt.setObjectName(u"paths_emailsTxt")
        self.paths_emailsTxt.setGeometry(QRect(0, 364, 840, 42))
        self.paths_emailsTxt_lineEdit = QLineEdit(self.paths_emailsTxt)
        self.paths_emailsTxt_lineEdit.setObjectName(u"paths_emailsTxt_lineEdit")
        self.paths_emailsTxt_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_emailsTxt_title = QLabel(self.paths_emailsTxt)
        self.paths_emailsTxt_title.setObjectName(u"paths_emailsTxt_title")
        self.paths_emailsTxt_title.setGeometry(QRect(-1, 1, 48, 18))
        self.paths_emailsTxt_title.setStyleSheet(u"")
        self.paths_emailsTxt_devider = QLabel(self.paths_emailsTxt)
        self.paths_emailsTxt_devider.setObjectName(u"paths_emailsTxt_devider")
        self.paths_emailsTxt_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_emailsTxt_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_emailsTxt_ext = QLabel(self.paths_emailsTxt)
        self.paths_emailsTxt_ext.setObjectName(u"paths_emailsTxt_ext")
        self.paths_emailsTxt_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_emailsTxt_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.pagination.addTab(self.n1, "")
        self.n2 = QWidget()
        self.n2.setObjectName(u"n2")
        self.paths_validAccountsTxt = QWidget(self.n2)
        self.paths_validAccountsTxt.setObjectName(u"paths_validAccountsTxt")
        self.paths_validAccountsTxt.setGeometry(QRect(0, 52, 840, 42))
        self.paths_validAccountsTxt_lineEdit = QLineEdit(self.paths_validAccountsTxt)
        self.paths_validAccountsTxt_lineEdit.setObjectName(u"paths_validAccountsTxt_lineEdit")
        self.paths_validAccountsTxt_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_validAccountsTxt_title = QLabel(self.paths_validAccountsTxt)
        self.paths_validAccountsTxt_title.setObjectName(u"paths_validAccountsTxt_title")
        self.paths_validAccountsTxt_title.setGeometry(QRect(0, 1, 112, 18))
        self.paths_validAccountsTxt_title.setStyleSheet(u"")
        self.paths_validAccountsTxt_devider = QLabel(self.paths_validAccountsTxt)
        self.paths_validAccountsTxt_devider.setObjectName(u"paths_validAccountsTxt_devider")
        self.paths_validAccountsTxt_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_validAccountsTxt_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_validAccountsTxt_ext = QLabel(self.paths_validAccountsTxt)
        self.paths_validAccountsTxt_ext.setObjectName(u"paths_validAccountsTxt_ext")
        self.paths_validAccountsTxt_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_validAccountsTxt_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_invalidAccountsTxt = QWidget(self.n2)
        self.paths_invalidAccountsTxt.setObjectName(u"paths_invalidAccountsTxt")
        self.paths_invalidAccountsTxt.setGeometry(QRect(0, 104, 840, 42))
        self.paths_invalidAccountsTxt_lineEdit = QLineEdit(self.paths_invalidAccountsTxt)
        self.paths_invalidAccountsTxt_lineEdit.setObjectName(u"paths_invalidAccountsTxt_lineEdit")
        self.paths_invalidAccountsTxt_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.paths_invalidAccountsTxt_title = QLabel(self.paths_invalidAccountsTxt)
        self.paths_invalidAccountsTxt_title.setObjectName(u"paths_invalidAccountsTxt_title")
        self.paths_invalidAccountsTxt_title.setGeometry(QRect(-1, 1, 128, 18))
        self.paths_invalidAccountsTxt_title.setStyleSheet(u"")
        self.paths_invalidAccountsTxt_devider = QLabel(self.paths_invalidAccountsTxt)
        self.paths_invalidAccountsTxt_devider.setObjectName(u"paths_invalidAccountsTxt_devider")
        self.paths_invalidAccountsTxt_devider.setGeometry(QRect(0, 20, 840, 2))
        self.paths_invalidAccountsTxt_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_invalidAccountsTxt_ext = QLabel(self.paths_invalidAccountsTxt)
        self.paths_invalidAccountsTxt_ext.setObjectName(u"paths_invalidAccountsTxt_ext")
        self.paths_invalidAccountsTxt_ext.setGeometry(QRect(806, 0, 34, 20))
        self.paths_invalidAccountsTxt_ext.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.paths_allAccountsTxt = QWidget(self.n2)
        self.paths_allAccountsTxt.setObjectName(u"paths_allAccountsTxt")
        self.paths_allAccountsTxt.setGeometry(QRect(0, 0, 840, 42))
        self.paths_allAccountsTxt_lineEdit_2 = QLineEdit(self.paths_allAccountsTxt)
        self.paths_allAccountsTxt_lineEdit_2.setObjectName(u"paths_allAccountsTxt_lineEdit_2")
        self.paths_allAccountsTxt_lineEdit_2.setGeometry(QRect(0, 22, 840, 20))
        self.paths_allAccountsTxt_title_2 = QLabel(self.paths_allAccountsTxt)
        self.paths_allAccountsTxt_title_2.setObjectName(u"paths_allAccountsTxt_title_2")
        self.paths_allAccountsTxt_title_2.setGeometry(QRect(0, 1, 96, 18))
        self.paths_allAccountsTxt_title_2.setStyleSheet(u"")
        self.paths_allAccountsTxt_devider_2 = QLabel(self.paths_allAccountsTxt)
        self.paths_allAccountsTxt_devider_2.setObjectName(u"paths_allAccountsTxt_devider_2")
        self.paths_allAccountsTxt_devider_2.setGeometry(QRect(0, 20, 840, 2))
        self.paths_allAccountsTxt_devider_2.setStyleSheet(u"background-color: #16e0ff;")
        self.paths_allAccountsTxt_ext_2 = QLabel(self.paths_allAccountsTxt)
        self.paths_allAccountsTxt_ext_2.setObjectName(u"paths_allAccountsTxt_ext_2")
        self.paths_allAccountsTxt_ext_2.setGeometry(QRect(806, 0, 34, 20))
        self.paths_allAccountsTxt_ext_2.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.pagination.addTab(self.n2, "")
        self.config.addTab(self.paths, "")
        self.attempts = QWidget()
        self.attempts.setObjectName(u"attempts")
        self.attempts_save_config = QPushButton(self.attempts)
        self.attempts_save_config.setObjectName(u"attempts_save_config")
        self.attempts_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.attempts_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.attempts_refresh_config = QPushButton(self.attempts)
        self.attempts_refresh_config.setObjectName(u"attempts_refresh_config")
        self.attempts_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.attempts_refresh_config.setStyleSheet(u"")
        self.attempts_sendClick = QWidget(self.attempts)
        self.attempts_sendClick.setObjectName(u"attempts_sendClick")
        self.attempts_sendClick.setGeometry(QRect(0, 55, 840, 42))
        self.attempts_sendClick_title = QLabel(self.attempts_sendClick)
        self.attempts_sendClick_title.setObjectName(u"attempts_sendClick_title")
        self.attempts_sendClick_title.setGeometry(QRect(-1, 1, 224, 18))
        self.attempts_sendClick_title.setStyleSheet(u"")
        self.attempts_sendClick_horizontalSlider = QSlider(self.attempts_sendClick)
        self.attempts_sendClick_horizontalSlider.setObjectName(u"attempts_sendClick_horizontalSlider")
        self.attempts_sendClick_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.attempts_sendClick_horizontalSlider.setStyleSheet(u"")
        self.attempts_sendClick_horizontalSlider.setOrientation(Qt.Horizontal)
        self.attempts_sendClick_qty = QLabel(self.attempts_sendClick)
        self.attempts_sendClick_qty.setObjectName(u"attempts_sendClick_qty")
        self.attempts_sendClick_qty.setGeometry(QRect(782, 0, 58, 20))
        self.attempts_sendClick_qty.setMinimumSize(QSize(0, 0))
        self.attempts_sendClick_qty.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.attempts_sendClick_qty.setAlignment(Qt.AlignCenter)
        self.attempts_sendClick_devider = QLabel(self.attempts_sendClick)
        self.attempts_sendClick_devider.setObjectName(u"attempts_sendClick_devider")
        self.attempts_sendClick_devider.setGeometry(QRect(0, 20, 840, 2))
        self.attempts_sendClick_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.attempts_getWord = QWidget(self.attempts)
        self.attempts_getWord.setObjectName(u"attempts_getWord")
        self.attempts_getWord.setGeometry(QRect(0, 107, 840, 42))
        self.attempts_getWord_title = QLabel(self.attempts_getWord)
        self.attempts_getWord_title.setObjectName(u"attempts_getWord_title")
        self.attempts_getWord_title.setGeometry(QRect(-1, 1, 296, 18))
        self.attempts_getWord_title.setStyleSheet(u"")
        self.attempts_getWord_horizontalSlider = QSlider(self.attempts_getWord)
        self.attempts_getWord_horizontalSlider.setObjectName(u"attempts_getWord_horizontalSlider")
        self.attempts_getWord_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.attempts_getWord_horizontalSlider.setStyleSheet(u"")
        self.attempts_getWord_horizontalSlider.setOrientation(Qt.Horizontal)
        self.attempts_getWord_devider = QLabel(self.attempts_getWord)
        self.attempts_getWord_devider.setObjectName(u"attempts_getWord_devider")
        self.attempts_getWord_devider.setGeometry(QRect(0, 20, 840, 2))
        self.attempts_getWord_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.attempts_getWord_qty = QLabel(self.attempts_getWord)
        self.attempts_getWord_qty.setObjectName(u"attempts_getWord_qty")
        self.attempts_getWord_qty.setGeometry(QRect(782, 0, 58, 20))
        self.attempts_getWord_qty.setMinimumSize(QSize(0, 0))
        self.attempts_getWord_qty.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.attempts_getWord_qty.setAlignment(Qt.AlignCenter)
        self.attempts_getConfirmUrl = QWidget(self.attempts)
        self.attempts_getConfirmUrl.setObjectName(u"attempts_getConfirmUrl")
        self.attempts_getConfirmUrl.setGeometry(QRect(0, 159, 840, 42))
        self.attempts_getConfirmUrl_title = QLabel(self.attempts_getConfirmUrl)
        self.attempts_getConfirmUrl_title.setObjectName(u"attempts_getConfirmUrl_title")
        self.attempts_getConfirmUrl_title.setGeometry(QRect(-1, 1, 312, 18))
        self.attempts_getConfirmUrl_title.setStyleSheet(u"")
        self.attempts_getConfirmUrl_horizontalSlider = QSlider(self.attempts_getConfirmUrl)
        self.attempts_getConfirmUrl_horizontalSlider.setObjectName(u"attempts_getConfirmUrl_horizontalSlider")
        self.attempts_getConfirmUrl_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.attempts_getConfirmUrl_horizontalSlider.setStyleSheet(u"")
        self.attempts_getConfirmUrl_horizontalSlider.setOrientation(Qt.Horizontal)
        self.attempts_getConfirmUrl_devider = QLabel(self.attempts_getConfirmUrl)
        self.attempts_getConfirmUrl_devider.setObjectName(u"attempts_getConfirmUrl_devider")
        self.attempts_getConfirmUrl_devider.setGeometry(QRect(0, 20, 840, 2))
        self.attempts_getConfirmUrl_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.attempts_getConfirmUrl_qty = QLabel(self.attempts_getConfirmUrl)
        self.attempts_getConfirmUrl_qty.setObjectName(u"attempts_getConfirmUrl_qty")
        self.attempts_getConfirmUrl_qty.setGeometry(QRect(782, 0, 58, 20))
        self.attempts_getConfirmUrl_qty.setMinimumSize(QSize(0, 0))
        self.attempts_getConfirmUrl_qty.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.attempts_getConfirmUrl_qty.setAlignment(Qt.AlignCenter)
        self.attempts_totalAttempts = QWidget(self.attempts)
        self.attempts_totalAttempts.setObjectName(u"attempts_totalAttempts")
        self.attempts_totalAttempts.setGeometry(QRect(0, 484, 840, 30))
        self.attempts_totalAttempts_title = QLabel(self.attempts_totalAttempts)
        self.attempts_totalAttempts_title.setObjectName(u"attempts_totalAttempts_title")
        self.attempts_totalAttempts_title.setGeometry(QRect(0, 8, 208, 18))
        self.attempts_totalAttempts_title.setStyleSheet(u"")
        self.attempts_totalAttempts_devider = QLabel(self.attempts_totalAttempts)
        self.attempts_totalAttempts_devider.setObjectName(u"attempts_totalAttempts_devider")
        self.attempts_totalAttempts_devider.setGeometry(QRect(0, 28, 840, 2))
        self.attempts_totalAttempts_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.attempts_totalAttempts_qty = QLabel(self.attempts_totalAttempts)
        self.attempts_totalAttempts_qty.setObjectName(u"attempts_totalAttempts_qty")
        self.attempts_totalAttempts_qty.setGeometry(QRect(720, 0, 120, 28))
        self.attempts_totalAttempts_qty.setStyleSheet(u"font-size: 24px;\n"
"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 0 8px;")
        self.attempts_totalAttempts_qty.setAlignment(Qt.AlignCenter)
        self.config.addTab(self.attempts, "")
        self.params = QWidget()
        self.params.setObjectName(u"params")
        self.params_sectorSize = QWidget(self.params)
        self.params_sectorSize.setObjectName(u"params_sectorSize")
        self.params_sectorSize.setGeometry(QRect(0, 55, 840, 42))
        self.params_sectorSize_title = QLabel(self.params_sectorSize)
        self.params_sectorSize_title.setObjectName(u"params_sectorSize_title")
        self.params_sectorSize_title.setGeometry(QRect(0, 1, 216, 18))
        self.params_sectorSize_title.setStyleSheet(u"")
        self.params_sectorSize_horizontalSlider = QSlider(self.params_sectorSize)
        self.params_sectorSize_horizontalSlider.setObjectName(u"params_sectorSize_horizontalSlider")
        self.params_sectorSize_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.params_sectorSize_horizontalSlider.setStyleSheet(u"")
        self.params_sectorSize_horizontalSlider.setOrientation(Qt.Horizontal)
        self.params_sectorSize_dots = QLabel(self.params_sectorSize)
        self.params_sectorSize_dots.setObjectName(u"params_sectorSize_dots")
        self.params_sectorSize_dots.setGeometry(QRect(774, 0, 66, 20))
        self.params_sectorSize_dots.setMinimumSize(QSize(66, 20))
        self.params_sectorSize_dots.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.params_sectorSize_dots.setAlignment(Qt.AlignCenter)
        self.params_sectorSize_devider = QLabel(self.params_sectorSize)
        self.params_sectorSize_devider.setObjectName(u"params_sectorSize_devider")
        self.params_sectorSize_devider.setGeometry(QRect(0, 20, 840, 2))
        self.params_sectorSize_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.params_save_config = QPushButton(self.params)
        self.params_save_config.setObjectName(u"params_save_config")
        self.params_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.params_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.params_refresh_config = QPushButton(self.params)
        self.params_refresh_config.setObjectName(u"params_refresh_config")
        self.params_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.params_refresh_config.setStyleSheet(u"")
        self.params_passwordLength = QWidget(self.params)
        self.params_passwordLength.setObjectName(u"params_passwordLength")
        self.params_passwordLength.setGeometry(QRect(0, 159, 840, 62))
        self.params_passwordLength_horizontalSlider = QSlider(self.params_passwordLength)
        self.params_passwordLength_horizontalSlider.setObjectName(u"params_passwordLength_horizontalSlider")
        self.params_passwordLength_horizontalSlider.setGeometry(QRect(0, 46, 840, 16))
        self.params_passwordLength_horizontalSlider.setStyleSheet(u"")
        self.params_passwordLength_horizontalSlider.setOrientation(Qt.Horizontal)
        self.params_passwordLength_letters = QLabel(self.params_passwordLength)
        self.params_passwordLength_letters.setObjectName(u"params_passwordLength_letters")
        self.params_passwordLength_letters.setGeometry(QRect(750, 0, 90, 20))
        self.params_passwordLength_letters.setMinimumSize(QSize(66, 20))
        self.params_passwordLength_letters.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.params_passwordLength_letters.setAlignment(Qt.AlignCenter)
        self.params_passwordLength_lineEdit = QLineEdit(self.params_passwordLength)
        self.params_passwordLength_lineEdit.setObjectName(u"params_passwordLength_lineEdit")
        self.params_passwordLength_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.params_passwordLength_lineEdit.setStyleSheet(u"QLineEdit:hover {\n"
"       border: none;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"       border:none;\n"
"}")
        self.params_passwordLength_lineEdit.setAlignment(Qt.AlignCenter)
        self.params_passwordLength_lineEdit.setReadOnly(True)
        self.params_passwordLength_title = QLabel(self.params_passwordLength)
        self.params_passwordLength_title.setObjectName(u"params_passwordLength_title")
        self.params_passwordLength_title.setGeometry(QRect(-1, 1, 120, 18))
        self.params_passwordLength_title.setStyleSheet(u"")
        self.params_passwordLength_devider = QLabel(self.params_passwordLength)
        self.params_passwordLength_devider.setObjectName(u"params_passwordLength_devider")
        self.params_passwordLength_devider.setGeometry(QRect(0, 20, 840, 2))
        self.params_passwordLength_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.params_maxAge = QWidget(self.params)
        self.params_maxAge.setObjectName(u"params_maxAge")
        self.params_maxAge.setGeometry(QRect(0, 107, 840, 42))
        self.params_maxAge_title = QLabel(self.params_maxAge)
        self.params_maxAge_title.setObjectName(u"params_maxAge_title")
        self.params_maxAge_title.setGeometry(QRect(0, 1, 112, 18))
        self.params_maxAge_title.setStyleSheet(u"")
        self.params_maxAge_horizontalSlider = QSlider(self.params_maxAge)
        self.params_maxAge_horizontalSlider.setObjectName(u"params_maxAge_horizontalSlider")
        self.params_maxAge_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.params_maxAge_horizontalSlider.setStyleSheet(u"")
        self.params_maxAge_horizontalSlider.setOrientation(Qt.Horizontal)
        self.params_maxAge_years = QLabel(self.params_maxAge)
        self.params_maxAge_years.setObjectName(u"params_maxAge_years")
        self.params_maxAge_years.setGeometry(QRect(766, 0, 74, 20))
        self.params_maxAge_years.setMinimumSize(QSize(66, 20))
        self.params_maxAge_years.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.params_maxAge_years.setAlignment(Qt.AlignCenter)
        self.params_maxAge_devider = QLabel(self.params_maxAge)
        self.params_maxAge_devider.setObjectName(u"params_maxAge_devider")
        self.params_maxAge_devider.setGeometry(QRect(0, 20, 840, 2))
        self.params_maxAge_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.params_webDriverImplictWait = QWidget(self.params)
        self.params_webDriverImplictWait.setObjectName(u"params_webDriverImplictWait")
        self.params_webDriverImplictWait.setGeometry(QRect(0, 231, 840, 42))
        self.params_webDriverImplictWait_title = QLabel(self.params_webDriverImplictWait)
        self.params_webDriverImplictWait_title.setObjectName(u"params_webDriverImplictWait_title")
        self.params_webDriverImplictWait_title.setGeometry(QRect(0, 1, 176, 18))
        self.params_webDriverImplictWait_title.setStyleSheet(u"")
        self.params_webDriverImplictWait_horizontalSlider = QSlider(self.params_webDriverImplictWait)
        self.params_webDriverImplictWait_horizontalSlider.setObjectName(u"params_webDriverImplictWait_horizontalSlider")
        self.params_webDriverImplictWait_horizontalSlider.setGeometry(QRect(0, 26, 840, 16))
        self.params_webDriverImplictWait_horizontalSlider.setStyleSheet(u"")
        self.params_webDriverImplictWait_horizontalSlider.setOrientation(Qt.Horizontal)
        self.params_webDriverImplictWait_secs = QLabel(self.params_webDriverImplictWait)
        self.params_webDriverImplictWait_secs.setObjectName(u"params_webDriverImplictWait_secs")
        self.params_webDriverImplictWait_secs.setGeometry(QRect(774, 0, 66, 20))
        self.params_webDriverImplictWait_secs.setMinimumSize(QSize(66, 20))
        self.params_webDriverImplictWait_secs.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;")
        self.params_webDriverImplictWait_secs.setAlignment(Qt.AlignCenter)
        self.params_webDriverImplictWait_devider = QLabel(self.params_webDriverImplictWait)
        self.params_webDriverImplictWait_devider.setObjectName(u"params_webDriverImplictWait_devider")
        self.params_webDriverImplictWait_devider.setGeometry(QRect(0, 20, 840, 2))
        self.params_webDriverImplictWait_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.config.addTab(self.params, "")
        self.proxy = QWidget()
        self.proxy.setObjectName(u"proxy")
        self.proxy_save_config = QPushButton(self.proxy)
        self.proxy_save_config.setObjectName(u"proxy_save_config")
        self.proxy_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.proxy_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.proxy_refresh_config = QPushButton(self.proxy)
        self.proxy_refresh_config.setObjectName(u"proxy_refresh_config")
        self.proxy_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.proxy_refresh_config.setStyleSheet(u"")
        self.proxy_type = QWidget(self.proxy)
        self.proxy_type.setObjectName(u"proxy_type")
        self.proxy_type.setGeometry(QRect(0, 55, 840, 42))
        self.proxy_type_lineEdit = QLineEdit(self.proxy_type)
        self.proxy_type_lineEdit.setObjectName(u"proxy_type_lineEdit")
        self.proxy_type_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.proxy_type_title = QLabel(self.proxy_type)
        self.proxy_type_title.setObjectName(u"proxy_type_title")
        self.proxy_type_title.setGeometry(QRect(0, 1, 32, 18))
        self.proxy_type_title.setStyleSheet(u"")
        self.proxy_type_devider = QLabel(self.proxy_type)
        self.proxy_type_devider.setObjectName(u"proxy_type_devider")
        self.proxy_type_devider.setGeometry(QRect(0, 20, 840, 2))
        self.proxy_type_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.proxy_type_eg = QLabel(self.proxy_type)
        self.proxy_type_eg.setObjectName(u"proxy_type_eg")
        self.proxy_type_eg.setGeometry(QRect(782, 0, 58, 20))
        self.proxy_type_eg.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.proxy_username = QWidget(self.proxy)
        self.proxy_username.setObjectName(u"proxy_username")
        self.proxy_username.setGeometry(QRect(0, 107, 840, 42))
        self.proxy_username_lineEdit = QLineEdit(self.proxy_username)
        self.proxy_username_lineEdit.setObjectName(u"proxy_username_lineEdit")
        self.proxy_username_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.proxy_username_title = QLabel(self.proxy_username)
        self.proxy_username_title.setObjectName(u"proxy_username_title")
        self.proxy_username_title.setGeometry(QRect(0, 1, 64, 18))
        self.proxy_username_title.setStyleSheet(u"")
        self.proxy_username_devider = QLabel(self.proxy_username)
        self.proxy_username_devider.setObjectName(u"proxy_username_devider")
        self.proxy_username_devider.setGeometry(QRect(0, 20, 840, 2))
        self.proxy_username_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.proxy_password = QWidget(self.proxy)
        self.proxy_password.setObjectName(u"proxy_password")
        self.proxy_password.setGeometry(QRect(0, 159, 840, 42))
        self.proxy_password_lineEdit = QLineEdit(self.proxy_password)
        self.proxy_password_lineEdit.setObjectName(u"proxy_password_lineEdit")
        self.proxy_password_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.proxy_password_title = QLabel(self.proxy_password)
        self.proxy_password_title.setObjectName(u"proxy_password_title")
        self.proxy_password_title.setGeometry(QRect(-1, 1, 64, 18))
        self.proxy_password_title.setStyleSheet(u"")
        self.proxy_password_devider = QLabel(self.proxy_password)
        self.proxy_password_devider.setObjectName(u"proxy_password_devider")
        self.proxy_password_devider.setGeometry(QRect(0, 20, 840, 2))
        self.proxy_password_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.proxy_hostname = QWidget(self.proxy)
        self.proxy_hostname.setObjectName(u"proxy_hostname")
        self.proxy_hostname.setGeometry(QRect(0, 211, 840, 42))
        self.proxy_hostname_lineEdit = QLineEdit(self.proxy_hostname)
        self.proxy_hostname_lineEdit.setObjectName(u"proxy_hostname_lineEdit")
        self.proxy_hostname_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.proxy_hostname_title = QLabel(self.proxy_hostname)
        self.proxy_hostname_title.setObjectName(u"proxy_hostname_title")
        self.proxy_hostname_title.setGeometry(QRect(0, 1, 64, 18))
        self.proxy_hostname_title.setStyleSheet(u"")
        self.proxy_hostname_devider = QLabel(self.proxy_hostname)
        self.proxy_hostname_devider.setObjectName(u"proxy_hostname_devider")
        self.proxy_hostname_devider.setGeometry(QRect(0, 20, 840, 2))
        self.proxy_hostname_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.proxy_hostname_eg = QLabel(self.proxy_hostname)
        self.proxy_hostname_eg.setObjectName(u"proxy_hostname_eg")
        self.proxy_hostname_eg.setGeometry(QRect(710, 0, 130, 20))
        self.proxy_hostname_eg.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.proxy_port = QWidget(self.proxy)
        self.proxy_port.setObjectName(u"proxy_port")
        self.proxy_port.setGeometry(QRect(0, 263, 840, 42))
        self.proxy_port_lineEdit = QLineEdit(self.proxy_port)
        self.proxy_port_lineEdit.setObjectName(u"proxy_port_lineEdit")
        self.proxy_port_lineEdit.setGeometry(QRect(0, 22, 840, 20))
        self.proxy_port_title = QLabel(self.proxy_port)
        self.proxy_port_title.setObjectName(u"proxy_port_title")
        self.proxy_port_title.setGeometry(QRect(-1, 1, 32, 18))
        self.proxy_port_title.setStyleSheet(u"")
        self.proxy_port_devider = QLabel(self.proxy_port)
        self.proxy_port_devider.setObjectName(u"proxy_port_devider")
        self.proxy_port_devider.setGeometry(QRect(0, 20, 840, 2))
        self.proxy_port_devider.setStyleSheet(u"background-color: #16e0ff;")
        self.proxy_port_eg = QLabel(self.proxy_port)
        self.proxy_port_eg.setObjectName(u"proxy_port_eg")
        self.proxy_port_eg.setGeometry(QRect(798, 0, 42, 20))
        self.proxy_port_eg.setStyleSheet(u"background-color: #16e0ff;\n"
"color: #111111;\n"
"padding: 1px;\n"
"")
        self.config.addTab(self.proxy, "")
        self.numpad = QWidget()
        self.numpad.setObjectName(u"numpad")
        self.numpad_2 = QWidget(self.numpad)
        self.numpad_2.setObjectName(u"numpad_2")
        self.numpad_2.setGeometry(QRect(170, 46, 500, 249))
        self.numpad_2.setMinimumSize(QSize(428, 0))
        self.numpad_2.setStyleSheet(u"#numpad QLineEdit  {\n"
"       border: 1px solid #16e0ff;\n"
"}")
        self.gridLayout_2 = QGridLayout(self.numpad_2)
        self.gridLayout_2.setObjectName(u"gridLayout_2")
        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.numpad_num_1 = QLineEdit(self.numpad_2)
        self.numpad_num_1.setObjectName(u"numpad_num_1")
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.numpad_num_1.sizePolicy().hasHeightForWidth())
        self.numpad_num_1.setSizePolicy(sizePolicy)
        self.numpad_num_1.setMinimumSize(QSize(0, 51))
        self.numpad_num_1.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_1.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout.addWidget(self.numpad_num_1)

        self.numpad_num_2 = QLineEdit(self.numpad_2)
        self.numpad_num_2.setObjectName(u"numpad_num_2")
        sizePolicy.setHeightForWidth(self.numpad_num_2.sizePolicy().hasHeightForWidth())
        self.numpad_num_2.setSizePolicy(sizePolicy)
        self.numpad_num_2.setMinimumSize(QSize(0, 51))
        self.numpad_num_2.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_2.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout.addWidget(self.numpad_num_2)

        self.numpad_num_3 = QLineEdit(self.numpad_2)
        self.numpad_num_3.setObjectName(u"numpad_num_3")
        sizePolicy.setHeightForWidth(self.numpad_num_3.sizePolicy().hasHeightForWidth())
        self.numpad_num_3.setSizePolicy(sizePolicy)
        self.numpad_num_3.setMinimumSize(QSize(0, 51))
        self.numpad_num_3.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_3.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout.addWidget(self.numpad_num_3)


        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)

        self.horizontalLayout_2 = QHBoxLayout()
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.numpad_num_4 = QLineEdit(self.numpad_2)
        self.numpad_num_4.setObjectName(u"numpad_num_4")
        sizePolicy.setHeightForWidth(self.numpad_num_4.sizePolicy().hasHeightForWidth())
        self.numpad_num_4.setSizePolicy(sizePolicy)
        self.numpad_num_4.setMinimumSize(QSize(0, 51))
        self.numpad_num_4.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_4.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_2.addWidget(self.numpad_num_4)

        self.numpad_num_5 = QLineEdit(self.numpad_2)
        self.numpad_num_5.setObjectName(u"numpad_num_5")
        sizePolicy.setHeightForWidth(self.numpad_num_5.sizePolicy().hasHeightForWidth())
        self.numpad_num_5.setSizePolicy(sizePolicy)
        self.numpad_num_5.setMinimumSize(QSize(0, 51))
        self.numpad_num_5.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_5.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_2.addWidget(self.numpad_num_5)

        self.numpad_num_6 = QLineEdit(self.numpad_2)
        self.numpad_num_6.setObjectName(u"numpad_num_6")
        sizePolicy.setHeightForWidth(self.numpad_num_6.sizePolicy().hasHeightForWidth())
        self.numpad_num_6.setSizePolicy(sizePolicy)
        self.numpad_num_6.setMinimumSize(QSize(0, 51))
        self.numpad_num_6.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_6.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_2.addWidget(self.numpad_num_6)


        self.gridLayout_2.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)

        self.horizontalLayout_3 = QHBoxLayout()
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.numpad_num_7 = QLineEdit(self.numpad_2)
        self.numpad_num_7.setObjectName(u"numpad_num_7")
        sizePolicy.setHeightForWidth(self.numpad_num_7.sizePolicy().hasHeightForWidth())
        self.numpad_num_7.setSizePolicy(sizePolicy)
        self.numpad_num_7.setMinimumSize(QSize(0, 51))
        self.numpad_num_7.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_7.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_3.addWidget(self.numpad_num_7)

        self.numpad_num_8 = QLineEdit(self.numpad_2)
        self.numpad_num_8.setObjectName(u"numpad_num_8")
        sizePolicy.setHeightForWidth(self.numpad_num_8.sizePolicy().hasHeightForWidth())
        self.numpad_num_8.setSizePolicy(sizePolicy)
        self.numpad_num_8.setMinimumSize(QSize(0, 51))
        self.numpad_num_8.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_8.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)
        self.numpad_num_8.setClearButtonEnabled(False)

        self.horizontalLayout_3.addWidget(self.numpad_num_8)

        self.numpad_num_9 = QLineEdit(self.numpad_2)
        self.numpad_num_9.setObjectName(u"numpad_num_9")
        sizePolicy.setHeightForWidth(self.numpad_num_9.sizePolicy().hasHeightForWidth())
        self.numpad_num_9.setSizePolicy(sizePolicy)
        self.numpad_num_9.setMinimumSize(QSize(0, 51))
        self.numpad_num_9.setMaximumSize(QSize(16777215, 53))
        self.numpad_num_9.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_3.addWidget(self.numpad_num_9)


        self.gridLayout_2.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)

        self.horizontalLayout_4 = QHBoxLayout()
        self.horizontalLayout_4.setObjectName(u"horizontalLayout_4")
        self.numpad_num_0 = QLineEdit(self.numpad_2)
        self.numpad_num_0.setObjectName(u"numpad_num_0")
        sizePolicy.setHeightForWidth(self.numpad_num_0.sizePolicy().hasHeightForWidth())
        self.numpad_num_0.setSizePolicy(sizePolicy)
        self.numpad_num_0.setMinimumSize(QSize(0, 52))
        self.numpad_num_0.setMaximumSize(QSize(156, 53))
        self.numpad_num_0.setAlignment(Qt.AlignBottom|Qt.AlignHCenter)

        self.horizontalLayout_4.addWidget(self.numpad_num_0)


        self.gridLayout_2.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)

        self.numpad_save_config = QPushButton(self.numpad)
        self.numpad_save_config.setObjectName(u"numpad_save_config")
        self.numpad_save_config.setGeometry(QRect(0, 10, 420, 35))
        self.numpad_save_config.setStyleSheet(u"border-right: 2px solid #0a0a0a;")
        self.numpad_refresh_config = QPushButton(self.numpad)
        self.numpad_refresh_config.setObjectName(u"numpad_refresh_config")
        self.numpad_refresh_config.setGeometry(QRect(420, 10, 420, 35))
        self.numpad_refresh_config.setStyleSheet(u"")
        self.config.addTab(self.numpad, "")
        self.config_reset_button = QPushButton(settings)
        self.config_reset_button.setObjectName(u"config_reset_button")
        self.config_reset_button.setGeometry(QRect(0, 550, 840, 30))

        self.retranslateUi(settings)

        self.config.setCurrentIndex(2)
        self.pagination.setCurrentIndex(1)


        QMetaObject.connectSlotsByName(settings)
    # setupUi

    def retranslateUi(self, settings):
        settings.setWindowTitle(QCoreApplication.translate("settings", u"Form", None))
        self.delays_installFacebook_title.setText(QCoreApplication.translate("settings", u"AFTER INSTALLING FACEBOOK", None))
        self.delays_installFacebook_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_installFacebook_devider.setText("")
        self.delays_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.delays_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.delays_openFacebook_title.setText(QCoreApplication.translate("settings", u"AFTER OPENING FACEBOOK", None))
        self.delays_openFacebook_devider.setText("")
        self.delays_openFacebook_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_sendClick_title.setText(QCoreApplication.translate("settings", u"AFTER CLICKING", None))
        self.delays_sendClick_devider.setText("")
        self.delays_sendClick_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_sendKeys_title.setText(QCoreApplication.translate("settings", u"AFTER PRESSING THE KEY", None))
        self.delays_sendKeys_devider.setText("")
        self.delays_sendKeys_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_getWord_title.setText(QCoreApplication.translate("settings", u"TIME PER ITERATION OF WORD CHECK", None))
        self.delays_getWord_devider.setText("")
        self.delays_getWord_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_getConfirmUrl_title.setText(QCoreApplication.translate("settings", u"TIME PER ITERATION TO GET CONFIRMATION URL", None))
        self.delays_getConfirmUrl_devider.setText("")
        self.delays_getConfirmUrl_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.delays_totalTime_title.setText(QCoreApplication.translate("settings", u"TOTAL TIME", None))
        self.delays_totalTime_devider.setText("")
        self.delays_totalTime_secs.setText(QCoreApplication.translate("settings", u"0.0 SECS", None))
        self.config.setTabText(self.config.indexOf(self.delays), QCoreApplication.translate("settings", u"DELAYS", None))
        self.paths_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.paths_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.paths_adbFolder_title.setText(QCoreApplication.translate("settings", u"ADB", None))
        self.paths_adbFolder_devider.setText("")
        self.paths_adbFolder_ext.setText(QCoreApplication.translate("settings", u"FOLDER", None))
        self.paths_facebookApk_title.setText(QCoreApplication.translate("settings", u"FACEBOOK", None))
        self.paths_facebookApk_devider.setText("")
        self.paths_facebookApk_ext.setText(QCoreApplication.translate("settings", u"APK", None))
        self.paths_proxifierApk_title.setText(QCoreApplication.translate("settings", u"PROXIFIER", None))
        self.paths_proxifierApk_devider.setText("")
        self.paths_proxifierApk_ext.setText(QCoreApplication.translate("settings", u"APK", None))
        self.paths_chromeDriverExe_title.setText(QCoreApplication.translate("settings", u"CHROME DRIVER", None))
        self.paths_chromeDriverExe_devider.setText("")
        self.paths_chromeDriverExe_ext.setText(QCoreApplication.translate("settings", u"EXE", None))
        self.paths_paddleOcrDetFolder_title.setText(QCoreApplication.translate("settings", u"PADDLE OCR DET", None))
        self.paths_paddleOcrDetFolder_devider.setText("")
        self.paths_paddleOcrDetFolder_ext.setText(QCoreApplication.translate("settings", u"FOLDER", None))
        self.paths_paddleOcrRecFolder_title.setText(QCoreApplication.translate("settings", u"PADDLE OCR REC", None))
        self.paths_paddleOcrRecFolder_devider.setText("")
        self.paths_paddleOcrRecFolder_ext.setText(QCoreApplication.translate("settings", u"FOLDER", None))
        self.paths_PaddleOcrDigitalDictTxt_title.setText(QCoreApplication.translate("settings", u"PADDLE OCR DIGITAL DICT", None))
        self.paths_PaddleOcrDigitalDictTxt_devider.setText("")
        self.paths_PaddleOcrDigitalDictTxt_ext.setText(QCoreApplication.translate("settings", u"TXT", None))
        self.paths_emailsTxt_title.setText(QCoreApplication.translate("settings", u"EMAILS", None))
        self.paths_emailsTxt_devider.setText("")
        self.paths_emailsTxt_ext.setText(QCoreApplication.translate("settings", u"TXT", None))
        self.pagination.setTabText(self.pagination.indexOf(self.n1), QCoreApplication.translate("settings", u"  1  ", None))
        self.paths_validAccountsTxt_title.setText(QCoreApplication.translate("settings", u"VALID ACCOUNTS", None))
        self.paths_validAccountsTxt_devider.setText("")
        self.paths_validAccountsTxt_ext.setText(QCoreApplication.translate("settings", u"TXT", None))
        self.paths_invalidAccountsTxt_title.setText(QCoreApplication.translate("settings", u"INVALID ACCOUNTS", None))
        self.paths_invalidAccountsTxt_devider.setText("")
        self.paths_invalidAccountsTxt_ext.setText(QCoreApplication.translate("settings", u"TXT", None))
        self.paths_allAccountsTxt_title_2.setText(QCoreApplication.translate("settings", u"ALL ACCOUNTS", None))
        self.paths_allAccountsTxt_devider_2.setText("")
        self.paths_allAccountsTxt_ext_2.setText(QCoreApplication.translate("settings", u"TXT", None))
        self.pagination.setTabText(self.pagination.indexOf(self.n2), QCoreApplication.translate("settings", u"  2  ", None))
        self.config.setTabText(self.config.indexOf(self.paths), QCoreApplication.translate("settings", u"PATHS", None))
        self.attempts_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.attempts_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.attempts_sendClick_title.setText(QCoreApplication.translate("settings", u"ITERATIONS PER CLICK ATTEMPT", None))
        self.attempts_sendClick_qty.setText(QCoreApplication.translate("settings", u"0 QTY", None))
        self.attempts_sendClick_devider.setText("")
        self.attempts_getWord_title.setText(QCoreApplication.translate("settings", u"ITERATIONS PER WORD RETRIEVAL ATTEMPT", None))
        self.attempts_getWord_devider.setText("")
        self.attempts_getWord_qty.setText(QCoreApplication.translate("settings", u"0 QTY", None))
        self.attempts_getConfirmUrl_title.setText(QCoreApplication.translate("settings", u"ITERATIONS PER CONFIRMATION URL ATTEMPT", None))
        self.attempts_getConfirmUrl_devider.setText("")
        self.attempts_getConfirmUrl_qty.setText(QCoreApplication.translate("settings", u"0 QTY", None))
        self.attempts_totalAttempts_title.setText(QCoreApplication.translate("settings", u"TOTAL ATTEMPTS", None))
        self.attempts_totalAttempts_devider.setText("")
        self.attempts_totalAttempts_qty.setText(QCoreApplication.translate("settings", u"0 QTY", None))
        self.config.setTabText(self.config.indexOf(self.attempts), QCoreApplication.translate("settings", u"ATTEMPTS", None))
        self.params_sectorSize_title.setText(QCoreApplication.translate("settings", u"SECTOR SIZE(LARGER->FASTER)", None))
        self.params_sectorSize_dots.setText(QCoreApplication.translate("settings", u"0 DOTS", None))
        self.params_sectorSize_devider.setText("")
        self.params_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.params_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.params_passwordLength_letters.setText(QCoreApplication.translate("settings", u"0 LETTERS", None))
        self.params_passwordLength_title.setText(QCoreApplication.translate("settings", u"PASSWORD LENGTH", None))
        self.params_passwordLength_devider.setText("")
        self.params_maxAge_title.setText(QCoreApplication.translate("settings", u"MAX PERSON AGE", None))
        self.params_maxAge_years.setText(QCoreApplication.translate("settings", u"0 YEARS", None))
        self.params_maxAge_devider.setText("")
        self.params_webDriverImplictWait_title.setText(QCoreApplication.translate("settings", u"WEBDRIVER IMPLICT WAIT", None))
        self.params_webDriverImplictWait_secs.setText(QCoreApplication.translate("settings", u"0 SECS", None))
        self.params_webDriverImplictWait_devider.setText("")
        self.config.setTabText(self.config.indexOf(self.params), QCoreApplication.translate("settings", u"PARAMS", None))
        self.proxy_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.proxy_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.proxy_type_title.setText(QCoreApplication.translate("settings", u"TYPE", None))
        self.proxy_type_devider.setText("")
        self.proxy_type_eg.setText(QCoreApplication.translate("settings", u"SOCKS5", None))
        self.proxy_username_title.setText(QCoreApplication.translate("settings", u"USERNAME", None))
        self.proxy_username_devider.setText("")
        self.proxy_password_title.setText(QCoreApplication.translate("settings", u"PASSWORD", None))
        self.proxy_password_devider.setText("")
        self.proxy_hostname_title.setText(QCoreApplication.translate("settings", u"HOSTNAME", None))
        self.proxy_hostname_devider.setText("")
        self.proxy_hostname_eg.setText(QCoreApplication.translate("settings", u"255.255.255.255", None))
        self.proxy_port_title.setText(QCoreApplication.translate("settings", u"PORT", None))
        self.proxy_port_devider.setText("")
        self.proxy_port_eg.setText(QCoreApplication.translate("settings", u"8080", None))
        self.config.setTabText(self.config.indexOf(self.proxy), QCoreApplication.translate("settings", u"PROXY", None))
        self.numpad_save_config.setText(QCoreApplication.translate("settings", u"SAVE CONFIG", None))
        self.numpad_refresh_config.setText(QCoreApplication.translate("settings", u"REFRESH CONFIG", None))
        self.config.setTabText(self.config.indexOf(self.numpad), QCoreApplication.translate("settings", u"NUMPAD", None))
        self.config_reset_button.setText(QCoreApplication.translate("settings", u"RESET CONFIG TO DEFAULT", None))
    # retranslateUi

